server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/language_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: anhnn   # bạn đặt mật khẩu cho MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update   # tự tạo bảng từ entity (chỉ dùng dev)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect